// AUTO-GENERATED by tools/codegen/regen.py from docs/isa/instructions.yaml.
// DO NOT EDIT BY HAND. Run `python -m tools.codegen.regen` to refresh.
//
// Source-of-truth checksum: 9e27eb5918cf8cd82ece0fb7d318a65c184af7acd7b5fcecf4acfe71b9c33c8f

#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace opengpu::isa {

inline constexpr int kWordBits     = 16;
inline constexpr int kDataBits     = 8;
inline constexpr int kAddrBits     = 8;
inline constexpr int kNumRegisters = 16;
inline constexpr int kNzpBits      = 3;

enum class Opcode : std::uint8_t {
    NOP = 0x0,
    BRnzp = 0x1,
    CMP = 0x2,
    ADD = 0x3,
    SUB = 0x4,
    MUL = 0x5,
    DIV = 0x6,
    LDR = 0x7,
    STR = 0x8,
    CONST = 0x9,
    ATOMICADD = 0xA,
    RET = 0xF,
};

enum class InsnType : std::uint8_t { R, I, B, Z };

struct Decoded {
    Opcode  op;
    InsnType type;
    std::uint8_t rd;        // R/I types
    std::uint8_t rs;        // R type
    std::uint8_t rt;        // R type
    std::uint8_t imm8;      // I type
    std::uint16_t imm9;     // B type (also branch target)
    std::uint8_t nzp;       // B type predicate

    // Mirrors the RTL decoder.sv output bus, bit-for-bit.
    std::uint8_t reg_write_enable;   // 1b
    std::uint8_t mem_read_enable;   // 1b
    std::uint8_t mem_write_enable;   // 1b
    std::uint8_t nzp_write_enable;   // 1b
    std::uint8_t reg_input_mux;   // 2b
    std::uint8_t alu_arithmetic_mux;   // 2b
    std::uint8_t alu_output_mux;   // 1b
    std::uint8_t pc_mux;   // 1b
    std::uint8_t ret;   // 1b
};

struct InsnSpec {
    Opcode op;
    std::string_view mnemonic;
    InsnType type;
    std::uint8_t reg_write_enable;
    std::uint8_t mem_read_enable;
    std::uint8_t mem_write_enable;
    std::uint8_t nzp_write_enable;
    std::uint8_t reg_input_mux;
    std::uint8_t alu_arithmetic_mux;
    std::uint8_t alu_output_mux;
    std::uint8_t pc_mux;
    std::uint8_t ret;
};

inline constexpr std::array<InsnSpec, 12> kInsnTable = {{
    InsnSpec{ Opcode::NOP, "NOP", InsnType::Z, 0, 0, 0, 0, 0, 0, 0, 0, 0 },
    InsnSpec{ Opcode::BRnzp, "BRnzp", InsnType::B, 0, 0, 0, 0, 0, 0, 0, 1, 0 },
    InsnSpec{ Opcode::CMP, "CMP", InsnType::R, 0, 0, 0, 1, 0, 0, 1, 0, 0 },
    InsnSpec{ Opcode::ADD, "ADD", InsnType::R, 1, 0, 0, 0, 0, 0, 0, 0, 0 },
    InsnSpec{ Opcode::SUB, "SUB", InsnType::R, 1, 0, 0, 0, 0, 1, 0, 0, 0 },
    InsnSpec{ Opcode::MUL, "MUL", InsnType::R, 1, 0, 0, 0, 0, 2, 0, 0, 0 },
    InsnSpec{ Opcode::DIV, "DIV", InsnType::R, 1, 0, 0, 0, 0, 3, 0, 0, 0 },
    InsnSpec{ Opcode::LDR, "LDR", InsnType::R, 1, 1, 0, 0, 1, 0, 0, 0, 0 },
    InsnSpec{ Opcode::STR, "STR", InsnType::R, 0, 0, 1, 0, 0, 0, 0, 0, 0 },
    InsnSpec{ Opcode::CONST, "CONST", InsnType::I, 1, 0, 0, 0, 2, 0, 0, 0, 0 },
    InsnSpec{ Opcode::ATOMICADD, "ATOMICADD", InsnType::R, 1, 1, 1, 0, 1, 0, 0, 0, 0 },
    InsnSpec{ Opcode::RET, "RET", InsnType::Z, 0, 0, 0, 0, 0, 0, 0, 0, 1 },
}};

// Look up the spec for an opcode value. Returns nullptr for unknown opcodes
// (the refsim treats those as a fault; the RTL silently no-ops).
inline const InsnSpec* lookup(std::uint8_t opcode) noexcept {
    for (const auto& s : kInsnTable) {
        if (static_cast<std::uint8_t>(s.op) == opcode) return &s;
    }
    return nullptr;
}

// Decode a 16-bit instruction word into the RTL-equivalent fields.
// This mirrors src/decoder.sv exactly so refsim and DUT agree on the same
// view of the ISA. Any divergence here is a bug.
inline Decoded decode(std::uint16_t word) noexcept {
    const std::uint8_t op4 = static_cast<std::uint8_t>((word >> 12) & 0xF);
    Decoded d{};
    const InsnSpec* spec = lookup(op4);
    if (spec == nullptr) {
        d.op   = static_cast<Opcode>(op4);
        d.type = InsnType::Z;
        return d;
    }
    d.op    = spec->op;
    d.type  = spec->type;
    d.rd    = static_cast<std::uint8_t>((word >> 8) & 0xF);
    d.rs    = static_cast<std::uint8_t>((word >> 4) & 0xF);
    d.rt    = static_cast<std::uint8_t>(word & 0xF);
    d.imm8  = static_cast<std::uint8_t>(word & 0xFF);
    d.imm9  = static_cast<std::uint16_t>(word & 0x1FF);
    d.nzp   = static_cast<std::uint8_t>((word >> 9) & 0x7);
    d.reg_write_enable = spec->reg_write_enable;
    d.mem_read_enable = spec->mem_read_enable;
    d.mem_write_enable = spec->mem_write_enable;
    d.nzp_write_enable = spec->nzp_write_enable;
    d.reg_input_mux = spec->reg_input_mux;
    d.alu_arithmetic_mux = spec->alu_arithmetic_mux;
    d.alu_output_mux = spec->alu_output_mux;
    d.pc_mux = spec->pc_mux;
    d.ret = spec->ret;
    return d;
}

}  // namespace opengpu::isa
