; AUTO-GENERATED by tools/codegen/regen.py from docs/isa/instructions.yaml.
; DO NOT EDIT BY HAND. Run `python -m tools.codegen.regen` to refresh.
;
; Source-of-truth checksum: 2a584d89125cfb63097d2d1957c22ce2653cd3efbc147d8d781115c50363e3d9
;
; customasm grammar for the OpenGPU 16-bit ISA.
; See https://github.com/hlorenzi/customasm for syntax reference.

#bits 16

#ruledef reg
{
    R0 => 0`4
    R1 => 1`4
    R2 => 2`4
    R3 => 3`4
    R4 => 4`4
    R5 => 5`4
    R6 => 6`4
    R7 => 7`4
    R8 => 8`4
    R9 => 9`4
    R10 => 10`4
    R11 => 11`4
    R12 => 12`4
    R13 => 13`4
    %blockIdx => 13`4
    R14 => 14`4
    %blockDim => 14`4
    R15 => 15`4
    %threadIdx => 15`4
}

#ruledef
{
    NOP => 0x0`4 @ 0`12
    BRnzp {nzp: u3}, {target: u9} => 0x1`4 @ nzp @ target
    CMP {rs: reg}, {rt: reg} => 0x2`4 @ 0`4 @ rs @ rt
    ADD {rd: reg}, {rs: reg}, {rt: reg} => 0x3`4 @ rd @ rs @ rt
    SUB {rd: reg}, {rs: reg}, {rt: reg} => 0x4`4 @ rd @ rs @ rt
    MUL {rd: reg}, {rs: reg}, {rt: reg} => 0x5`4 @ rd @ rs @ rt
    DIV {rd: reg}, {rs: reg}, {rt: reg} => 0x6`4 @ rd @ rs @ rt
    LDR {rd: reg}, {rs: reg} => 0x7`4 @ rd @ rs @ 0`4
    STR {rs: reg}, {rt: reg} => 0x8`4 @ 0`4 @ rs @ rt
    CONST {rd: reg}, {imm: u8} => 0x9`4 @ rd @ imm
    RET => 0xF`4 @ 0`12
}
