"""Tiny ``UOp`` -> OpenGPU asm lowering for elementwise binary kernels.

This is the smallest non-trivial codegen we can ship to demonstrate the
OpenGPU backend story. It accepts a textual operator name (``add``, ``sub``,
``mul``) and emits a SPMD kernel that maps one element to one thread, using
``%threadIdx`` (R15) as the lane index.

Memory layout produced (matches ``bench/kernels/vecadd``):

    [0,    n) : input a
    [n,   2n) : input b
    [2n,  3n) : output c

The emitted asm is the *same* text format consumed by ``tools.asm.asm`` so
this stays a thin string transformer with no hidden ABI.
"""

from __future__ import annotations

_OPS = {"add": "ADD", "sub": "SUB", "mul": "MUL"}


def emit_elementwise(op: str, n: int) -> str:
    """Return OpenGPU asm for ``c[tid] = a[tid] <op> b[tid]`` over ``n`` lanes.

    Parameters
    ----------
    op:
        One of ``add``, ``sub``, ``mul`` (mirrors the corresponding
        OpenGPU R-type opcodes).
    n:
        Number of elements / threads. Must satisfy ``1 <= n <= 16`` and
        ``3*n <= 256`` (8-bit address space).
    """
    if op not in _OPS:
        raise ValueError(f"unsupported op '{op}'; expected one of {sorted(_OPS)}")
    if not 1 <= n <= 16:
        raise ValueError(f"n out of range: {n}")
    if 3 * n > 256:
        raise ValueError(f"3*n exceeds 8-bit memory: {3 * n}")

    mnemonic = _OPS[op]
    return (
        f"; auto-generated by tools.tinygrad_opengpu.codegen.emit_elementwise\n"
        f"; op={op} n={n}\n"
        f"  CONST R3, #0\n"
        f"  CONST R4, #{n}\n"
        f"  CONST R5, #{2 * n}\n"
        f"  ADD   R6, R3, R15\n"
        f"  ADD   R7, R4, R15\n"
        f"  ADD   R8, R5, R15\n"
        f"  LDR   R9,  R6\n"
        f"  LDR   R10, R7\n"
        f"  {mnemonic:<5} R11, R9, R10\n"
        f"  STR   R8, R11\n"
        f"  RET\n"
    )


# Convenience alias used in the module docstring example.
def emit_vecadd(n: int) -> str:
    return emit_elementwise("add", n)
